services:
  weather_api:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: weather_api
      command: ["./entrypoint.sh"]
      environment:
        - SECRET_KEY=${SECRET_KEY}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
      ports:
        - "8000:8000"
      depends_on:
        postgres-primary:
          condition: service_healthy
        pgbouncer:
          condition: service_started
      networks:
      - app-network
  weather_collector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_collector
    command: celery -A weather_analyzer worker --loglevel=info --queues=collector_queue --concurrency=4
    environment:
        - SECRET_KEY=${SECRET_KEY}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
    depends_on:
      - redis
      - weather_api
    networks:
      - app-network
  weather_processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_processor
    command: celery -A weather_analyzer worker --loglevel=info --queues=processor_queue --concurrency=4
    environment:
        - SECRET_KEY=${SECRET_KEY}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
    depends_on:
      - redis
      - weather_api
    networks:
      - app-network

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-beat
    command: celery -A weather_analyzer beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - weather_api
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: always
      
  postgres-primary:
    image: bitnami/postgresql:15
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_REPLICATION_MODE=${POSTGRESQL_PRIMARY_REPLICATION_MODE}
      - POSTGRESQL_REPLICATION_USER=${POSTGRESQL_REPLICATION_USER}
      - POSTGRESQL_REPLICATION_PASSWORD=${POSTGRESQL_REPLICATION_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_EXTRA_FLAGS=${POSTGRESQL_EXTRA_FLAGS}
    healthcheck:
      test: pg_isready -U postgres -d weather
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  postgres-replica:
    image: bitnami/postgresql:15
    restart: always
    depends_on:
      postgres-primary:
        condition: service_healthy
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_REPLICATION_MODE=${POSTGRESQL_REPLICA_REPLICATION_MODE} 
      - POSTGRESQL_REPLICATION_USER=${POSTGRESQL_REPLICATION_USER}
      - POSTGRESQL_REPLICATION_PASSWORD=${POSTGRESQL_REPLICATION_PASSWORD}
      - POSTGRESQL_MASTER_HOST=${POSTGRESQL_MASTER_HOST}
      - POSTGRESQL_MASTER_PORT_NUMBER=${POSTGRESQL_MASTER_PORT_NUMBER}
    networks:
      - app-network
  pgbouncer:
    image: docker.io/bitnami/pgbouncer:1
    ports:
      - "5432:6432"
    environment:
      - POSTGRESQL_HOST=postgres-primary
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - PGBOUNCER_DATABASE=${PGBOUNCER_DATABASE}
      - PGBOUNCER_AUTH_TYPE=${PGBOUNCER_AUTH_TYPE}
      - PGBOUNCER_POOL_MODE=${PGBOUNCER_POOL_MODE}
      - PGBOUNCER_MAX_CLIENT_CONN=${PGBOUNCER_MAX_CLIENT_CONN}
      - PGBOUNCER_DSN_0=${PGBOUNCER_DSN_0}
    depends_on:
      - postgres-primary
    networks:
      - app-network

networks:
  app-network:
    driver: bridge